export { default as Cart } from './mainScreenCart/mainScreenCart'
export { default as StyleText } from './styleText/styleText'
export { default as LocationDisabledModal } from './locationDisabledModal'
export { default as BluetoothDisabledModal } from './bluetoothDisabledModal/bluetoothDisabledModal' 
export { default as SwitchLocation } from './switchLocation/switchLocation'